version: "3"

services:
  frontend:
    container_name: manic_frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - TZ=Europe/Berlin
    networks:
      - manicweb-network

  

  proxy:
    image: nginx:latest
    restart: always
    container_name: manicweb_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 80
    depends_on:
      - frontend
    networks:
      - manicweb-network
      - traefik-main
    environment:
      - TZ=Europe/Berlin


networks:
  traefik-main:
  manicweb-network:
    driver: bridge